language: julia

os:
  - linux
  - osx

julia:
  - 1.2
  - 1.4

notifications:
  email: false

# Install Julia dependencies, Miniconda, and Snakemake
install:
  - julia --project=SSPS --eval 'using Pkg; Pkg.instantiate()'
  - julia --project=SSPS SSPS/precompile_script.jl
  # Download OS-specific version of Miniconda installer
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda3-py37_4.8.2-Linux-x86_64.sh -O miniconda.sh
    fi
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda3-py37_4.8.2-MacOSX-x86_64.sh -O miniconda.sh
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - source $HOME/miniconda/etc/profile.d/conda.sh
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda create -n ssps -c bioconda -c conda-forge python=3.7 snakemake
  - conda activate ssps
  - pip install csvdiff

script:
  - cd tests
  - bash ssps_csv.sh

