# This directory (*ABSOLUTE* path) will contain the intermediate
# results for all of the analyses.
# You need to change it to fit your circumstances,
# e.g., "/scratch" or wherever you have plenty of disk available.
#temp_dir: "/home/dmerrell/projects/graph_ppl/temp"
temp_dir: "/ua/dmerrell/dbn_mcmc_temp"

# Define the convergence analysis
convergence_analysis:
    simulation_grid:
        V: [200] #,100,500]
        R: [0.25]
        A: [0.25]
        T: [8]
        M: 4     # number of time series to generate
    N: 3 #5 # number of simulation replicates 
    experimental_datasets:
        - "hill-egfr"
        - "big-egfr"
    max_samples: 50000
    timeout: 2400 #86400 # one day 
    burnin: 0.5
    stop_points: [500, 1000, 2000, 5000, 6500, 10000, 20000, 50000] #, 100000]
    psrf_ub: 1.01
    neff_per_chain: 10.0
    n_chains: 4
    mcmc_hyperparams:
        regression_deg: [1]


# Define the simulation study
simulation_study:
    # timeout for each method 
    timeout: 7200 # seconds
    # the grid of simulated datasets
    simulation_grid:
        V: [100] #, 100] #, 200]     # number of variables
        R: [0.1, 0.5, 1.0]    # fraction of edges to remove
        A: [0.1, 0.5, 1.0]    # fraction of new edges to add
        T: [8] #, 20]             # length of each time series 
        M: 4                   # number of time series
    # polynomial degree used by autoregression *data generator*
    polynomial_degree: 3
    # Number of simulations at each grid point
    N: 1
    # the grid of MCMC hyperparameters
    mcmc_hyperparams:
        burnin: 0.5 
        regression_deg: [1] 
        max_samples: 50000
        n_chains: 2


hill_timetest:
    degs: [1, 2] #, 3, 4, 5]
    v: [20] #, 100, 1000]
    modes: ["linear"] #, "quadratic", "full"]
    deg_v_combs: [[1,20], [1,100], [1,1000], 
                  [2,20], [2,100], [2,1000]] #, 
                  #[3,20],[3,100],
                  #[4,20],
                  #[5,20]]
    timeout: 30 #3600


