# This directory (*ABSOLUTE* path) will contain the intermediate
# results for all of the analyses.
# You need to change it to fit your circumstances,
# e.g., "/scratch" or wherever you have plenty of disk available.
#temp_dir: "/home/dmerrell/projects/graph_ppl/temp"
temp_dir: "/z/Proj/dmerrell_mcmc/graph-ppl/temp"
#temp_dir: "/mnt/ws/home/dmerrell/projects/graph-ppl/temp"

# Define the convergence analysis
convergence_analysis:
    simulation_grid:
        V: [20,100,500]
        R: [0.5, 1.0]
        A: [0.5, 1.0]
        T: [8]
        M: 4     # number of time series to generate
    N: 5 # number of simulation replicates 
    experiments:
        cell_lines: ["BT20", "BT549", "MCF7", "UACC812"]
        stimuli: ["EGF", "FGF1", "HGF", "IGF1", "Insulin", "NRG1", "PBS", "Serum"]
    max_samples: 100000
    timeout: 43200 #86400 # one day 
    burnin: 0.5
    stop_points: [500, 1000, 2000, 5000, 10000, 20000, 50000, 100000] 
    psrf_ub: 1.01
    neff_per_chain: 10.0
    n_chains: 4
    mcmc_hyperparams:
        regression_deg: [1,3]


# Define the simulation study
simulation_study:
    # timeout for each method 
    timeout: 10800 # seconds
    # the grid of simulated datasets
    simulation_grid:
        V: [20, 100, 500]     # number of variables
        R: [0.1, 0.5, 0.75, 1.0]    # fraction of edges to remove
        A: [0.1, 0.5, 0.75, 1.0]    # fraction of new edges to add
        T: [8] #, 20]             # length of each time series 
        M: 4                   # number of time series
    # polynomial degree used by autoregression *data generator*
    polynomial_degree: 3
    # Number of simulations at each grid point
    N: 5
    # the grid of MCMC hyperparameters
    mcmc_hyperparams:
        burnin: 0.5 
        regression_deg: [1,3] 
        max_samples: 100000
        n_chains: 2


hill_timetest:
    degs: [1, 2] #, 3, 4, 5]
    v: [20] #, 100, 1000]
    modes: ["linear"] #, "quadratic", "full"]
    deg_v_combs: [[1,20], [1,100], [1,1000], 
                  [2,20], [2,100], [2,1000]] #, 
                  #[3,20],[3,100],
                  #[4,20],
                  #[5,20]]
    timeout: 30 #3600



experimental_analysis:
    dream_ts_relpath: "dream-challenge/raw/timeseries"
    dream_ref_relpath: "dream-challenge/raw/ref_graph"


