# This directory (*ABSOLUTE* path) will contain the intermediate
# results for all of the analyses.
# The default empty string ("") creates a "temp" subdirectory in the current working directory.
# You may need to change it to fit your circumstances,
# e.g., "/scratch" or wherever you have plenty of disk available.
temp_dir: "" 

# Define the simulation study
simulation_study:
    # the grid of simulated datasets
    simulation_grid:
        V: [40, 100, 200]           # number of variables
        R: [0.1, 0.5, 0.75, 1.0]    # fraction of edges to remove
        A: [0.1, 0.5, 0.75, 1.0]    # fraction of new edges to add
        T: [8]                      # length of each time series 
        M: 4                        # number of time series
    # polynomial degree used by autoregression *data generator*
    polynomial_degree: 3
    # Number of simulations at each grid point
    convergence:
        timeout: 43200
        stop_points: [100, 1000, 5000, 10000, 20000, 50000, 100000]
        psrf_ub: 1.1
        neff_per_chain: 10.0 
        n_chains: 4
        N: 5
    prediction:
        timeout: 43200 
        n_chains: 4
        N: 5
    # the grid of MCMC hyperparameters
    mcmc_hyperparams:
        burnin: 0.5 
        regression_deg: [1]  
        max_samples: 100000
        lambda_prop_std: [3.0] 
        large_indeg: 15
    baseline_methods: ["funchisq", "lasso", "hill", "prior_baseline", "uniform"]

dream_challenge: 
    cell_lines: ["BT20", "BT549", "MCF7", "UACC812"]
    stimuli: ["EGF", "FGF1", "HGF", "IGF1", "Insulin", "NRG1", "PBS", "Serum"]
    N: 5
    convergence:
        stop_points: [100, 1000, 5000, 10000, 20000, 50000, 100000]
        psrf_ub: 1.1
        neff_per_chain: 10.0 
    mcmc_hyperparams:
        timeout: 43200
        burnin: 0.5 
        regression_deg: [1]  
        max_samples: 100000
        lambda_prop_std: [3.0] 
        large_indeg: 15
        n_chains: 4
    baseline_methods: ["hill", "funchisq", "lasso", "prior_baseline"]


hill_timetest:
    modes: ["full"] # ["linear", "quadratic", "full"]
    deg_v_combs: [[1,40], [1,100], [1,200], 
                  [2,40], [2,100], [2,200], 
                  [3,40], [3,100], [3,200],
                  [4,40], #[4,100], [4,200],
                  [5,40], #[5,100], [5,200],
                  [6,40]] #,
                  #[7,40]]
    timeout: 43200
    mem_mb: 32000




