name: Test SSPS

on:
- push
- pull_request

jobs:
  test:
    name: Test SSPS
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: ['1.6']
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
      - name: Install Julia packages
        run: |
          julia --project=SSPS --eval 'using Pkg; Pkg.instantiate()'
          julia --project=SSPS SSPS/precompile_script.jl
      - name: Install conda environment with Snakemake
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: ssps
          environment-file: tests/environment.yml
          auto-activate-base: false
          miniconda-version: 'latest'
      - name: Run SSPS test
        shell: bash --login {0}
        run: |
          cd tests
          bash ssps_csv.sh
